// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTt2TBzNZs6GJfMzB0HJDpbkKB8p6dcBM',
    appId: '1:950597604396:web:21cfb807a541503a3ced89',
    messagingSenderId: '950597604396',
    projectId: 'studyo-projesi',
    authDomain: 'studyo-projesi.firebaseapp.com',
    storageBucket: 'studyo-projesi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKM4ag0dzGCj3QwTlOoBRoa5h_B7LiNzc',
    appId: '1:950597604396:android:b704fac0a3238ff23ced89',
    messagingSenderId: '950597604396',
    projectId: 'studyo-projesi',
    storageBucket: 'studyo-projesi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3NKdwR3C3R5OGU6slShj4PRHVbJsz6HU',
    appId: '1:950597604396:ios:d2cf5bfc75cf68683ced89',
    messagingSenderId: '950597604396',
    projectId: 'studyo-projesi',
    storageBucket: 'studyo-projesi.firebasestorage.app',
    iosBundleId: 'com.example.studyoProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3NKdwR3C3R5OGU6slShj4PRHVbJsz6HU',
    appId: '1:950597604396:ios:d2cf5bfc75cf68683ced89',
    messagingSenderId: '950597604396',
    projectId: 'studyo-projesi',
    storageBucket: 'studyo-projesi.firebasestorage.app',
    iosBundleId: 'com.example.studyoProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTt2TBzNZs6GJfMzB0HJDpbkKB8p6dcBM',
    appId: '1:950597604396:web:1c88594c64a617053ced89',
    messagingSenderId: '950597604396',
    projectId: 'studyo-projesi',
    authDomain: 'studyo-projesi.firebaseapp.com',
    storageBucket: 'studyo-projesi.firebasestorage.app',
  );
}
